"""Shared GE constants."""

SAMPLE_SUB_OBJECTIVE_NAME = "示例子目标"
SAMPLE_PROGRAM_NAME = "示例专项"
SAMPLE_PROJECT_NAME = "示例项目"
SAMPLE_PHASE_NAME = "示例阶段"
SYSTEM_START_PHASE_NAME = "开始"
SYSTEM_END_PHASE_NAME = "结束"
SYSTEM_START_TASK_TITLE = "启动项目"
SYSTEM_END_TASK_TITLE = "结项复盘"
SYSTEM_END_SIGN_TASK_TITLE = "确认结项"
SYSTEM_START_GATE_ITEM_NAME = "团队共识"
SYSTEM_END_GATE_ITEM_NAME = "团队复盘"
# Pre-rename stock names (migration + dual-match until backfill).
LEGACY_SYSTEM_START_GATE_ITEM_NAME = "项目启动"
LEGACY_SYSTEM_END_GATE_ITEM_NAME = "结项复盘"
SYSTEM_START_GATE_ITEM_NAMES = frozenset(
    {SYSTEM_START_GATE_ITEM_NAME, LEGACY_SYSTEM_START_GATE_ITEM_NAME}
)
SYSTEM_END_GATE_ITEM_NAMES = frozenset(
    {SYSTEM_END_GATE_ITEM_NAME, LEGACY_SYSTEM_END_GATE_ITEM_NAME}
)
PROPOSAL_PHASE_NAME = "方案"
PROPOSAL_GATE_ITEM_NAME = "解决方案"
PROPOSAL_RESEARCH_TASK_TITLE = "调研和编写方案"
PROPOSAL_REVIEW_TASK_TITLE = "评审方案"
TASK_STATUS_IDLE = ""
TASK_STATUS_DEVIATED = "deviated"
